CREATE TABLE orderinfo (
         orderid int unsigned NOT NULL AUTO_INCREMENT primary key,
         uid CHAR(32),
         username CHAR(32)  NOT NULL,
         ordertype CHAR(16),
         factory CHAR(32),
         factorynumber  CHAR(32),
         productionline CHAR(16),
         materielid CHAR(32) NOT NULL,
         customid CHAR(32) NOT NULL,
         customname CHAR(64) NOT NULL,
         custombatch CHAR(64) NOT NULL,
         customnote CHAR(64),
         produceid CHAR(32),
         note CHAR(64),
         creattime  CHAR(32),
		 creatstamp BIGINT NOT NULL,
		 lastTime BIGINT NOT NULL,
         producetime CHAR(32),
         successtime CHAR(32),
         ordernum  double,
         producenum double,
         successnum double,
         totlemoney double,
         money double,
         printnum int,
         curflow CHAR(32)
)ENGINE = INNODB DEFAULT CHARSET = utf8mb4;