CREATE TABLE orderinfo (
         orderid int unsigned NOT NULL AUTO_INCREMENT primary key,
         ordertype CHAR(16),
         uid CHAR(32),
         username CHAR(32)  NOT NULL,
         materielid CHAR(32) NOT NULL,
         customid CHAR(32) NOT NULL,
         customname CHAR(64) NOT NULL,
         custombatch CHAR(64) NOT NULL,
         customnote CHAR(64),
         totlemoney double,
         money double,
         ordernum  double,
         producenum double,
         successnum double,
         producetime CHAR(32),
         successtime CHAR(32),
         creattime  CHAR(32),
         creatstamp BIGINT NOT NULL,
         lasttime BIGINT NOT NULL
)ENGINE = INNODB DEFAULT CHARSET = utf8mb4;