     CREATE TABLE material (
         materid int unsigned NOT NULL AUTO_INCREMENT primary key,
         materdes CHAR(254)  NOT NULL unique key ,
         cid CHAR(32) NOT NULL,
         customname CHAR(64) NOT NULL,
         plating  CHAR(32),
         friction CHAR(32),
         thickness CHAR(32),
         salt CHAR(32),
         componentsolid CHAR(32) NOT NULL,
         componentformat CHAR(32),
         factory CHAR(16),
         productionline CHAR(16),
         unit CHAR(16),
         money double,
         creattime  CHAR(32),
		 creatstamp BIGINT NOT NULL,
		 lastTime BIGINT NOT NULL,
         KEY `idx_cid_solid` (`cid`,`componentsolid`)
     )ENGINE = INNODB DEFAULT CHARSET = utf8mb4;